### ISSUE TITLE
New-AzureRmAppServicePlan : Method not found: 

### ISSUE THREAD

**Issue by Flodu31** [Azure/azure-docs-powershell#558] opened 2018-04-25 06:57 UTC
Hi,
On Azure Automation, I've the following error:

`New-AzureRmAppServicePlan : Method not found: 'Newtonsoft.Json.Serialization.IAttributeProvider 
Newtonsoft.Json.Serialization.JsonProperty.get_AttributeProvider()'.
At line:23 char:1
+ New-AzureRmAppServicePlan -Name $webappname -Location $location -Reso ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmAppServicePlan], MissingMethodException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.AppServicePlans.NewAzureAppServicePlanCmdlet
`
It's working fine on my computer.
PowerShell module is 4.2.2.

Any idea?
Thanks.
FLorent

**Comment by Flodu31** [comment] 2018-04-25 07:11
With version 5.0.0 (in preview) I've no error.

**Comment by TaraMeyer** [comment] 2018-05-14 18:08
@Flodu31  I am closing this request as the issue is resolved in the 5.7.0 and in 6.0.0.

**Closed by TaraMeyer** 2018-05-14 18:08 UTC
