### ISSUE TITLE
Checking which versions are installed

### ISSUE THREAD

**Issue by cbailiss** [Azure/azure-docs-powershell#634] opened 2018-06-29 09:51 UTC
It would be helpful to include an example of how to check the version(s) that is/are installed, e.g.
Import-Module AzureRM
Get-Module -Name AzureRM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2064497d-2f2f-1e6c-1c6b-c3a7090acbbc
* Version Independent ID: 9a312576-d1c8-6a00-c1ff-b52677b16e17
* Content: [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/uninstall-azurerm-ps?view=azurermps-6.3.0)
* Content Source: [docs-conceptual/azurermps-6.3.0/uninstall-azurerm-ps.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.3.0/uninstall-azurerm-ps.md)
* Product: **powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment] 2018-06-29 17:24
Duplicate of #633

**Closed by sptramer** 2018-06-29 17:24 UTC
Labels: duplicate, triaged

**Comment by cbailiss** [comment] 2018-06-29 20:29
Hi @sptramer 
I believe there is still a need to describe (or link to) how to check the versions that are installed on this docs page.  I.e. the page talks about specifying a specific version to uninstall.  How do I know which version to select unless I can check which version(s) is/are installed.  That might sound too simple/obvious, but I don't use Azure PS every day (like many people, only a small percentage of the IT services we provide are currently provisioned via Azure) and sometimes it is the lack of doc info for these simple tasks that is frustrating and hinders us from using Azure more.  Hope that helps.

**Comment by hawkbox** [comment] 2018-11-21 20:47
I'm running into a problem removing versions, it just fails on a parameter and the option for removing all installed versions fails right up until it removed 6.9.0.

PS C:\Powershell> Get-Module -Name AzureRM -List | select Name,Version

Name    Version
----    -------
AzureRM 5.5.0  
AzureRM 5.1.1  
AzureRM 6.13.1 



PS C:\Powershell> 
PS C:\Powershell> Uninstall-AllModules -TargetModule AzureRM -Version 6.13.1 -Force
Creating list of dependencies...
Uninstalling AzureRM.Profile version 
	Cannot validate argument on parameter 'RequiredVersion'. The argument is null. Provide a valid value for the argument, and then try running the command again.
