### ISSUE TITLE
Set-AzureRmStorageAccount is wrong

### ISSUE THREAD

**Issue by robinsh** [Azure/azure-docs-powershell#442] opened 2017-10-19 22:38 UTC
The --force parameter's information is missing. It shows the info for the access tiers instead. It actually looks as if the information for the -Force parameter and a parameter name after that got accidentally removed. 

Also, same thing for -Tag. The information is wrong, and the parameter Kind is missing. (It has the explanation for Kind right after the heading for -Tag.)

**Comment by TaraMeyer** [comment] 2017-11-13 17:48
@robinsh - sorry for the delay in response.  Can you please take a look at the latest version for this cmdlet and see if the issue is resolved:  https://docs.microsoft.com/en-us/powershell/module/azurerm.storage/set-azurermstorageaccount.

PS:  These values are towards the bottom of the page in the optional parameters section.

Thanks!

**Comment by robinsh** [comment] 2017-11-13 18:21
Under "-KeyName", what the heck does this mean: "Storage Account encryption keySource KeyVault KeyName" ?  
Also, note that "Storage Account" is not a product, and should not be capitalized. Of course if it starts the sentence, it should be "Storage account ... " 
Under "-KeyVaultUti", what does "Storage Account encryption keySource KeyVault KeyVaultUri" mean? Same question for "KeyVersion". 
Under -Name", why is modify capitalized? 
Under "-AccessTier", the link to the hot and cold storage tiers information is messed up.
Under "-DefaultProfile", please capitalize Azure.
Under "-DisableEncryptionService", it's "Storage Service Encryption" -- this is a feature -- and you can remove "on the Storage Service". That's redundant. Also, should be "Azure Blob storage and Azure Files are supported."  They rarely refer to them as services, and Files was rebranched at Ignite last September.
Under "-EnableEncryptionService", should be "Storage Service Encryption" and remove "on the Storage Service". Also, "Azure Blob storage and Azure Files are supported."
Under "-EnableHttpsTrafficOnly", lowercase storage account, and it should be "enables", not "enable". And HTTPS. 
Under "

**Comment by TaraMeyer** [comment] 2017-11-13 23:18
@robinsh - sounds like you need to talk to the devs that created this module; they own the cotent.  I created this pr for you to track in the source repo:  https://github.com/Azure/azure-powershell/issues/4979.

**Comment by robinsh** [comment] 2017-11-13 23:40
@TaraMeyer Ok, that's fine. Someone told me to post errors as issues to the GitHub, repo, and I didn't look at the other variables at first, hence my comments.

**Comment by TaraMeyer** [comment] 2017-11-13 23:41
@robinsh - no worries.  If you don't get much traction in the next few weeks on the pr above, let me know and I see if I can get you directly in touch with the engineering team.

**Comment by TaraMeyer** [comment] 2017-12-01 18:24
@robinsh  - I see this update is still open in the src.  I followed up with you and Wei Wei on the open pr.

**Comment by TaraMeyer** [comment] 2018-01-04 18:59
@robinsh - looks like the corresponding issue has been fixed at the source: Azure/azure-powershell#4979..  I am closing this issue for now, please let me know if you have any questions.  Thanks!

**Closed by TaraMeyer** 2018-01-04 18:59 UTC
